import StringIO
import dexy.artifact
import dexy.plugin
import logging
import os
import shutil

class Reporter(dexy.plugin.Plugin):
    """
    Base class for types of reporter.
    """
    ALIASES = []
    __metaclass__ = dexy.plugin.PluginMeta

    _SETTINGS = {
            "default" : ("Whether to run this report by default. Should be False for reports with side effects.", True),
            "dir" : ("Top-level directory in which report will be stored", None),
            "readme-filename" : ("Name of README file.", "README"),
            "safety-filename" : ("Name of a file which will be created in generated dir, and checked before generated dir is removed.", ".dexy-generated"),
            }
    _UNSET = []

    @classmethod
    def is_active(klass):
        return True

    def create_reports_dir(self, reports_dir=None):
        if not reports_dir:
            reports_dir = self.setting('dir')

        if not reports_dir:
            return False

        self.remove_reports_dir(reports_dir, keep_empty_dir=True)

        safety_filepath = os.path.join(reports_dir, self.setting('safety-filename'))
        readme_filepath = os.path.join(reports_dir, self.setting('readme-filename'))

        if not os.path.exists(reports_dir):
            os.mkdir(reports_dir)

        with open(safety_filepath, "w") as f:
            f.write("""
            This directory was generated by the %s Dexy Reporter and
            may be deleted without notice.\n\n""" % self.__class__.__name__)
        with open(readme_filepath, "w") as f:
            f.write("""
            This directory was generated by the %s Dexy Reporter and
            may be deleted without notice.\n\n""" % self.__class__.__name__)

    def remove_reports_dir(self, reports_dir=None, keep_empty_dir=False):
        if not reports_dir:
            reports_dir = self.setting('dir')

        if not reports_dir:
            return False

        safety_filepath = os.path.join(reports_dir, self.setting('safety-filename'))

        if os.path.exists(reports_dir) and not os.path.exists(safety_filepath):
            raise Exception("Please remove directory %s, Dexy wants to put a report here but doesn't want to overwrite anything by accident." % os.path.abspath(reports_dir))
        elif os.path.exists(reports_dir):
            if keep_empty_dir:
                # Does not remove the base directory, useful if you are running
                # a process (like 'dexy serve') from inside that directory
                for f in os.listdir(reports_dir):
                    path = os.path.join(reports_dir, f)
                    if os.path.isdir(path):
                        shutil.rmtree(path)
                    else:
                        os.remove(path)
            else:
                shutil.rmtree(reports_dir)

    def run(self, wrapper):
        pass

    def set_log(self):
        if not hasattr(self, 'log'):
            self.log = logging.getLogger("report:%s" % self.ALIASES[0])
            self.logstream = StringIO.StringIO()
            handler = logging.StreamHandler(self.logstream)
            if hasattr(self, 'wrapper'):
                handler.setFormatter(logging.Formatter(self.wrapper.log_format))
            self.log.addHandler(handler)
            self.log.setLevel(logging.DEBUG)

            try:
                self.log.addHandler(logging.getLogger('dexy').handlers[0])
            except IndexError:
                pass
