#!/bin/bash -ex

find . -name "*.pyc" -exec rm -rf {} \;

rm -rf testenv/
virtualenv --no-site-packages testenv/

source testenv/bin/activate

pip install .
pip install GitPython
nosetests
dexy reset
dexy --directory test-examples --danger
dexy report --allreports
dexy --directory test-examples --danger
dexy report --allreports
dexy --directory test-examples --danger --uselocals no
dexy report --allreports

pip install z3c.checkversions
checkversions

deactivate


rm -rf testenv/
virtualenv --no-site-packages -p python2.6 testenv/
source testenv/bin/activate

pip install .
pip install GitPython
nosetests
dexy reset
dexy --directory test-examples --danger
dexy report --allreports
dexy --directory test-examples --danger
dexy report --allreports
dexy --directory test-examples --danger --uselocals no
dexy report --allreports

deactivate

