#!/bin/bash -ex

rm -rf testenv/
virtualenv --no-site-packages testenv/

source testenv/bin/activate

pip install .
nosetests
dexy reset
dexy --directory test-template/
dexy report --allreports
dexy --directory test-template/
dexy report --allreports

pip install z3c.checkversions
checkversions

deactivate


rm -rf testenv/
virtualenv --no-site-packages -p python2.6 testenv/
source testenv/bin/activate

pip install .
nosetests
dexy reset
dexy --directory test-template/
dexy report --allreports
dexy --directory test-template/
dexy report --allreports

deactivate

