= Dexy Developer Documentation
:toc:
:source-highlighter: pygments

{% macro src(fn, section, language="python") %}
[source,{{ language }}]
----
{{ d['/' + fn + '|pydoc'][section + ":source"] }}
----
{% endmacro %}


== Welcome

This is internal developer documentation for dexy. Its primary purpose is to
help improve the quality of dexy code.

== Command Line Interface

The command line interface for dexy is driven by
https://pypi.python.org/pypi/python-modargs[python-modargs].

=== init.py

Any function ending with `_command` is automatically exposed as a command. To
keep modules to a manageable size, the various dexy commands are defined in
different modules, but all are imported into `dexy.commands` in the
`__init__.py` file so they can be available to modargs within a single module:

{{ d['/dexy/commands/__init__.py|idio|asciisyn']['import-all-commands'] }}

The `run` method in `dexy.commands` is listed in `setup.py` as a console script entry point:

{{ d['/setup.py|idio|asciisyn']['entry-points'] }}

And this is the first method which will be called whenever a user enters a `dexy` command:

{{ src('dexy/commands/__init__.py', 'run') }}

The `capture_warnings` method just hides irrelevant warning messages from dexy users:

{{ src('dexy/commands/__init__.py', 'capture_warnings') }}

Dexy can load a lot of different libraries as it runs various filters, and
deprecation messages and similar warnings are confusing and annoying for end
users.

The `resolve_argv` method is called next:

{{ src('dexy/commands/__init__.py', 'resolve_argv') }}

It's possible for additional commands to be added to dexy via the plugin
system.  For example, the `dexy-viewer` plugin defines a `ping` command which
can be called as follows:

{{ d['commands.sh|idio|shint|asciisyn']['ping'] }}

{{ d['/tests/test_commands.py|idio|asciisyn']['viewer-ping'] }}

If necessary the `resolve_argv` command calls `resolve_plugin_command` to
look in dexy plugins for the requested command:

{{ src('dexy/commands/__init__.py', 'resolve_plugin_command') }}

Returning to the `run` command we started with:

{{ src('dexy/commands/__init__.py', 'run') }}

The parsed arguments, module object and a default command are passed to
`parse_and_run_cmd` which delegates to the modargs command of the same name,
and wraps the call with error handling to provide nicer error messages if
there's a problem:

{{ src('dexy/commands/__init__.py', 'parse_and_run_cmd') }}

The `help` and `version` commands are also defined in the `__init__.py` file:

{{ src('dexy/commands/__init__.py', 'help_command') }}

{{ src('dexy/commands/__init__.py', 'version_command') }}

=== cite.py

The `dexy cite` command prints out an academic citation for dexy.

{{ src('dexy/commands/cite.py', 'cite_command') }}

{{ d['commands.sh|idio|shint|asciisyn']['cite'] }}

Currently the bibtex format is supported:

{{ src('dexy/commands/cite.py', 'bibtex_text') }}

=== conf.py

The main dexy command has a lot of command line options, and for convenience
you can save the option values in a `dexy.conf` file in your project so you
don't have to remember and type them all the time. The `dexy conf` command
generates an example file for you containing all the default dexy options:

{{ src('dexy/commands/conf.py', 'conf_command') }}

{{ d['commands.sh|idio|shint|asciisyn']['conf'] }}

If a config file already exists, or if you use the `-p` flag, then config
options are written to stdout instead of written to a file.

{{ d['/tests/test_commands.py|idio|asciisyn']['conf'] }}

=== dirs.py

These commands expose methods for creating and removing dexy's working directories.

The `setup` and `cleanup` command create and remove working directories respectively:

{{ src('dexy/commands/dirs.py', 'setup_command') }}

{{ src('dexy/commands/dirs.py', 'cleanup_command') }}

The `reset` command cleans out any working files and leaves you with a fresh setup:

{{ src('dexy/commands/dirs.py', 'reset_command') }}

=== fcmds.py

Filter commands are intended to be a way for filters to expose some information
to users. For example, filter commands could provide a way for an API to list
available methods.

{{ src('dexy/commands/fcmds.py', 'fcmds_command') }}

The `fcmds_command` lists filter commands:

{{ d['commands.sh|idio|shint|asciisyn']['fcmds'] }}

To run a filter command you need to pass the alias and the command name:

{{ d['commands.sh|idio|shint|asciisyn']['run-fcmd'] }}

{{ src('dexy/commands/fcmds.py', 'fcmd_command') }}

=== filters.py

The filters module contains dexy's command line reference for filters.

{{ src('dexy/commands/filters.py', 'filters_command') }}

{{ src('dexy/commands/filters.py', 'help_for_filter') }}

{{ src('dexy/commands/filters.py', 'list_filters') }}

=== grep.py

The grep interface is a way to search on the command line for dexy docs and
keys within docs.  The dexy viewer plugin presents similar information in a
web-based interface.


