import dexy.plugins.archive_filters
import dexy.plugins.example_filters
import dexy.plugins.file_extension_filters
import dexy.plugins.idio_filters
import dexy.plugins.latex_filters
import dexy.plugins.markdown_filters
import dexy.plugins.nltk_filter
import dexy.plugins.output_reporters
import dexy.plugins.pexpect_filters
import dexy.plugins.pydoc_filters
import dexy.plugins.pygments_filters
import dexy.plugins.restructured_text_filters
import dexy.plugins.split_filters
import dexy.plugins.standard_filters
import dexy.plugins.stationery
import dexy.plugins.stdout_filters
import dexy.plugins.subprocess_filters
import dexy.plugins.templating_filters
