import dexy.plugins.archive_filters
import dexy.plugins.example_filters
import dexy.plugins.idio_filters
import dexy.plugins.markdown_filters
import dexy.plugins.nltk_filter
import dexy.plugins.output_reporters
import dexy.plugins.pygments_filters
import dexy.plugins.split_filters
import dexy.plugins.standard_filters
import dexy.plugins.stationery
import dexy.plugins.stdout_filters
import dexy.plugins.templating_filters
import dexy.plugins.xdoc_filters
